### ISSUE TITLE
Use Task Module

### ISSUE THREAD

**Issue by Riptide0108** [OfficeDev/microsoft-teams-apps-faqplusv2#13]
Hi, 
Has anyone been successful using the new features of v2, specifically the Task Modules?
How can we access the Task Module from the Expert Channel?
Is there any documentation available for that?

Thanks in advancel

**Comment by AmitKhot2508** [comment]
Hi @Riptide0108,

In expert team go to messaging extension. On right top you can see '+' button. Upon clicking on button the task module gets open.

![image](https://user-images.githubusercontent.com/57248245/78252731-ec251080-7510-11ea-9d54-d0a38fb02a05.png)

**Comment by abbodh** [comment]
hi @Riptide0108 - closing the thread. In case you are facing any other issue, then please open a new issue.
