### ISSUE TITLE
Knowledgebase ID is not valid

### ISSUE THREAD

**Issue by Koxzi95** [OfficeDev/microsoft-teams-apps-faqplusv2#18]
Hi there, 

Working with an organisation to get this deployed and we're getting Knowledgebase ID is not valid on the config site per the image. 
![kbid-kan](https://user-images.githubusercontent.com/6239399/80738093-634bc580-8b0c-11ea-919c-66254d0a1081.jpg)

It looks as though the ConfigurationItems table hasn't populated during the deployment.

**Comment by coderkrishna92** [comment]
Hi @Koxzi95 have you published the knowledge base correctly? Also can you double check your QnA Maker API Endpoint URL in the Configuration settings on the Azure portal please?

**Comment by Koxzi95** [comment]
Hi there @coderkrishna92 everything was deployed and published correctly as far as I could see when reviewing the deployment. We deleted and redeployed all components and it worked fine. Apologies I can't provide much more info or root cause.
