### ISSUE TITLE
App Service wont sync to get app code. 

### ISSUE THREAD

**Issue by pgr-jeremy-m** [OfficeDev/microsoft-teams-apps-faqplusv2#25]
Once the deployment is complete the app service for the bot wont sync up with the repo to download app code. 

Source : External Git
Repo : https://github.com/OfficeDev/microsoft-teams-apps-faqplusv2.git
Error : 

Command: deploy.cmd
Handling ASP.NET Core Web Application deployment.
MSBUILD : 
error MSB1025: An internal failure occurred while running MSBuild.
System.ComponentModel.Win32Exception (5): Access is denied.
   at System.Diagnostics.Process.set_PriorityClassCore(ProcessPriorityClass value)
   at System.Diagnostics.Process.set_PriorityClass(ProcessPriorityClass value)
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine)
Failed exitCode=-532462766, command=dotnet restore "D:\home\site\repository\Source\Microsoft.Teams.Apps.FAQPlusPlus.sln"
An error has occurred during web site deployment.
Unhandled exception. System.ComponentModel.Win32Exception (5): Access is denied.
   at System.Diagnostics.Process.set_PriorityClassCore(ProcessPriorityClass value)
   at System.Diagnostics.Process.set_PriorityClass(ProcessPriorityClass value)
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine)
   at Microsoft.Build.CommandLine.MSBuildApp.Main(String[] args)
Unhandled exception. System.ComponentModel.Win32Exception (5): Access is denied.\r\n   at System.Diagnostics.Process.set_PriorityClassCore(ProcessPriorityClass value)\r\n   at System.Diagnostics.Process.set_PriorityClass(ProcessPriorityClass value)\r\n   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine)\r\n   at Microsoft.Build.CommandLine.MSBuildApp.Main(String[] args)\r\nD:\Program Files (x86)\SiteExtensions\Kudu\87.20522.4610\bin\Scripts\starter.cmd deploy.cmd

**Comment by bungleweed** [comment]
It's an issue with the dotnet SDK version updating to 3.1.301 I believe. https://stackoverflow.com/questions/62595408/error-access-is-denied-deployment-to-azure-app-services/62597620#62597620

**Comment by pgr-jeremy-m** [comment]
Thanks @bungleweed that was the issue exactly.   Closing.
