### ISSUE TITLE
Experts bot doesn't use channel configured

### ISSUE THREAD

**Issue by Koxzi95** [OfficeDev/microsoft-teams-apps-faqplusv2#7]
When deploying this into a Team and selecting the channel it does not use this channel. The general channel is used for all messages.

**Comment by abbodh** [comment]
Thanks for sharing the feedback. Currently the app only uses General channel to send notifications, which is configured from admin configuration web application.

**Comment by Koxzi95** [comment]
Thanks for the answer! Shall look into changing via admin.
